### PR TITLE
Add capability to create Target dir + Travis Fix + Code Modularization 

### PR DESCRIPTION
**Pull request by vedantpuri**
- If target dir doesn't exist, ask if user wants to create a new one
- Travis file uses "--with-default-names" option while installing make, but that is not supported by brew as of January 2019 according to [this StackOverflow Post](https://stackoverflow.com/questions/30003570/how-to-use-gnu-sed-on-mac-os-x). Solves #18 (Tried it on my fork, see passed build [here](https://travis-ci.org/vedantpuri/linux-timemachine/builds/491349477))
- Create functions for arg parsing and validity
- Short circuited conditionals with exits to make code cleaner

### CODE REVIEW

**Comment by vedantpuri** [comment]
@cytopia Glad to see some activity on this PR. Hope you plan to merge this soon!

**Comment by cytopia** [comment]
@vedantpuri Travis CI will be replaced by GitHub Actions. See PR here: Will be replaced with GitHub Actions: #32

**Comment by cytopia** [comment]
@vedantpuri 

> If target dir doesn't exist, ask if user wants to create a new one

This should not be interactive as the script should be usable via cron as well.

**Comment by cytopia** [comment]
@vedantpuri 

The PR is now quite behind the current code. The two outstanding improvements:

* Create functions for arg parsing and validity
* Short circuited conditionals with exits to make code cleaner

will require some refactoring. Not sure if they still make sense. WDYT?

**Comment by vedantpuri** [comment]
> @vedantpuri
> 
> The PR is now quite behind the current code. The two outstanding improvements:
> 
> * Create functions for arg parsing and validity
> * Short circuited conditionals with exits to make code cleaner
> 
> will require some refactoring. Not sure if they still make sense. WDYT?

@cytopia I have not been actively following the repository, but at the time I made the commit I think it was a useful thing to have. But it surely makes sense to refactor them to maintain consistency with the latest code! I am not sure if I would be able to do that, but feel free to do that in this PR.

**Comment by cytopia** [comment]
> > @vedantpuri
> > The PR is now quite behind the current code. The two outstanding improvements:
> > 
> > * Create functions for arg parsing and validity
> > * Short circuited conditionals with exits to make code cleaner
> > 
> > will require some refactoring. Not sure if they still make sense. WDYT?
> 
> @cytopia I have not been actively following the repository, but at the time I made the commit I think it was a useful thing to have. But it surely makes sense to refactor them to maintain consistency with the latest code! I am not sure if I would be able to do that, but feel free to do that in this PR.

OK, I will close it then as it has diverged too much. Adding this now would mean to change basically everything and currently the code seems to be pretty stable, so I'd rather keep it this way to continue to ensure everything works as expected.

Thanks nevertheless for this contribution, I was simply to slow to take care about this.

**Pull request closed without merging**
