### PR TITLE
Fix the location of the latest backup

### PR DESCRIPTION
**Pull request by andreyfedoseev**
Latest backup should be located in destination folder, not in the current working folder.

### CODE REVIEW

**Comment by cytopia** [comment]
@andreyfedoseev 

I've already applied this change and updated this PR accordingly:

```diff
- if test -L ".../${BACKUP_LATEST}"; then
+ if test -L "${DEST}/${BACKUP_LATEST}"; then
```

However,  the following breaks CI
```diff
- --link-dest="../${BACKUP_LATEST}" \
+ --link-dest="${DEST}/${BACKUP_LATEST}" \
```

**Comment by achembarpu** [comment]
@cytopia Thanks for this amazing script!

> ```diff
> - --link-dest="../${BACKUP_LATEST}" \
> + --link-dest="${DEST}/${BACKUP_LATEST}" \
> ```

From my reading of https://github.com/cytopia/linux-timemachine/pull/24, it appears that the above change is quite important to ensuring the current backup is correctly linked? If so, will this PR be merged soon?

**Comment by cytopia** [comment]
> @cytopia Thanks for this amazing script!
> 
> > ```diff
> > - --link-dest="../${BACKUP_LATEST}" \
> > + --link-dest="${DEST}/${BACKUP_LATEST}" \
> > ```
> 
> From my reading of #24, it appears that the above change is quite important to ensuring the current backup is correctly linked? If so, will this PR be merged soon?

@achembarpu by the time this PR was created `timemachine` was in a very old state. It has now received a lot of fixes as well as SSH support and extensive CI tests to ensure everything works as expected.

The option listed above does break backups on Linux as well as SSH backups in general.

In my opinion this option is not required, the CI tests ensure that it is linked correctly afterwards and check the size of a second incremental backup, which is then way smaller than the initial one. So this should give you enough confidence that it works as expected.

If this does not work for you, can you please provide some steps to reproduce, I will then integrate it into the CI checks to ensure this issue is caught correctly on all platforms and will address a fix to it.

**Comment by achembarpu** [comment]
@cytopia Thanks for the detailed reply! :)

I have been scouring github for good backup programs, and linux-timemachine seems like a perfect match to my requirements. Usually before I set up, I usually scan OSS projects' issues/PRs for any outstanding bugs.

I found it interesting that this seemingly important issue was unmerged. So I thought I would enquire why. It's good to understand the reasoning and I completely agree! I would recommend closing this PR and re-open only if someone can reproduce.

In the meanwhile, I shall try this tool out :D Thanks @cytopia !

**Comment by cytopia** [comment]
@andreyfedoseev I will mark the remaining part of this PR (thanks for all the other input) as invalid and close it now, as the current state has been proven and tested to work as expected.

**Pull request closed without merging**
